import type { MatchImportSpec } from "@/lib/import/match-import-service";

/** Zaandijk VR1 — actief seizoen 2025/26. Kickoffs: 12:00 UTC op de speeldag (aanpasbaar in beheer). */
export const ZAANDIJK_VR1_2025_26_SPECS: MatchImportSpec[] = [
  {
    kickoffIso: "2025-09-20T12:00:00.000Z",
    opponent: "WSV 1930 VR1",
    isHome: true,
    goalsFor: 0,
    goalsAgainst: 0,
    goalRows: [],
    mvpRaw: "Marisha Prins",
  },
  {
    kickoffIso: "2025-10-01T12:00:00.000Z",
    opponent: "ZOB VR1",
    isHome: false,
    goalsFor: 1,
    goalsAgainst: 3,
    goalRows: [{ scorerName: "Emma de Mie" }],
    mvpRaw: "Emma de Mie",
  },
  {
    kickoffIso: "2025-10-04T12:00:00.000Z",
    opponent: "VV Egmond VR1",
    isHome: false,
    goalsFor: 1,
    goalsAgainst: 2,
    /** Uitslag uitwedstrijd 2–1 = één goal Zaandijk; eerste genoemde scorer. */
    goalRows: [{ scorerName: "Nienke Hoffman" }],
    mvpRaw: "Mandy Kalmeijer",
  },
  {
    kickoffIso: "2025-10-11T12:00:00.000Z",
    opponent: "VV Assendelft (Velserbroek)",
    isHome: false,
    goalsFor: 3,
    goalsAgainst: 1,
    goalRows: [
      { scorerName: "Nienke Hoffman", assistName: "Tess Luijting" },
      { scorerName: "Shura Nieboer" },
      { scorerName: "Shura Nieboer" },
    ],
    mvpRaw: "Melissa Donkers",
  },
  {
    kickoffIso: "2025-11-08T12:00:00.000Z",
    opponent: "Stormvogels ijvv VR1",
    isHome: false,
    goalsFor: 9,
    goalsAgainst: 0,
    goalRows: [
      { scorerName: "Andrada Timmer", assistName: "Dionne van Dijk" },
      { scorerName: "Andrada Timmer", assistName: "Dionne van Dijk" },
      { scorerName: "Melissa Rietveld", assistName: "Dionne van Dijk" },
      { scorerName: "Melissa Rietveld", assistName: "Dionne van Dijk" },
      { scorerName: "Emma de Mie", assistName: "Melissa Rietveld" },
      { scorerName: "Emma de Mie", assistName: "Melissa Rietveld" },
      { scorerName: "Nienke Hoffman", assistName: "Renée Koopman" },
      { scorerName: "Nienke Hoffman", assistName: "Anouk Aafjes" },
      { scorerName: "Dionne van Dijk", assistName: "Shura Nieboer" },
    ],
    mvpRaw: "Andrada Timmer",
  },
  {
    draftPlaceholder: true,
    kickoffIso: undefined,
    opponent: "Sporting Andijk VR1",
    isHome: true,
    goalsFor: 3,
    goalsAgainst: 2,
    goalRows: [
      { scorerName: "Pitou Ludding" },
      { scorerName: "Nienke Hoffman" },
      { scorerName: "Emma de Mie" },
    ],
    mvpRaw: "Jelisa De Jonge",
  },
  {
    kickoffIso: "2025-12-06T12:00:00.000Z",
    opponent: "Wieringermeer VR2",
    isHome: false,
    goalsFor: 1,
    goalsAgainst: 1,
    goalRows: [{ scorerName: "Pitou Ludding" }],
    mvpRaw: "Marisha Prins",
  },
  {
    kickoffIso: "2025-12-13T12:00:00.000Z",
    opponent: "Wieringermeer VR3",
    isHome: false,
    goalsFor: 1,
    goalsAgainst: 2,
    goalRows: [{ scorerName: "Melissa Rietveld", assistName: "Mandy Kalmeijer" }],
    mvpRaw: "Marisha Prins",
  },
  {
    kickoffIso: "2026-01-24T12:00:00.000Z",
    opponent: "ZVC'22 VR1",
    isHome: true,
    goalsFor: 12,
    goalsAgainst: 0,
    goalRows: [
      { scorerName: "Melissa Rietveld", assistName: "Mandy Kalmeijer" },
      { scorerName: "Melissa Rietveld", assistName: "Mandy Kalmeijer" },
      { scorerName: "Melissa Rietveld", assistName: "Mandy Kalmeijer" },
      { scorerName: "Nienke Hoffman", assistName: "Andrada Timmer" },
      { scorerName: "Nienke Hoffman", assistName: "Renée Koopman" },
      { scorerName: "Nienke Hoffman" },
      { scorerName: "Pitou Ludding" },
      { scorerName: "Pitou Ludding" },
      { scorerName: "Andrada Timmer" },
      { scorerName: "Esmee" },
      { scorerName: "Esmee" },
      { scorerName: "Kyra De Bakker" },
    ],
    mvpRaw: "Nienke Hoffman",
  },
  {
    kickoffIso: "2026-01-31T12:00:00.000Z",
    opponent: "WSV 1930 VR1",
    isHome: false,
    goalsFor: 4,
    goalsAgainst: 1,
    goalRows: [
      { scorerName: "Pitou Ludding", assistName: "Emma de Mie" },
      { scorerName: "Pitou Ludding", assistName: "Nienke Hoffman" },
      { scorerName: "Micah", assistName: "Pitou Ludding" },
      { scorerName: "Nienke Hoffman" },
    ],
    mvpRaw: "Pitou Ludding",
  },
  {
    kickoffIso: "2026-02-07T12:00:00.000Z",
    opponent: "ZOB VR1",
    isHome: true,
    goalsFor: 1,
    goalsAgainst: 3,
    goalRows: [{ scorerName: "Mandy Kalmeijer", assistName: "Melissa Rietveld" }],
    mvpRaw: "Marisha Prins",
  },
  {
    kickoffIso: "2026-03-07T12:00:00.000Z",
    opponent: "VV Assendelft (Velserbroek)",
    isHome: true,
    goalsFor: 3,
    goalsAgainst: 0,
    goalRows: [
      { scorerName: "Shura Nieboer", assistName: "Dionne van Dijk" },
      { scorerName: "Andrada Timmer", assistName: "Melissa Rietveld" },
      { scorerName: "Andrada Timmer" },
    ],
    mvpRaw: "Andrada Timmer",
  },
  {
    kickoffIso: "2026-03-11T12:00:00.000Z",
    opponent: "VV Egmond VR1",
    isHome: true,
    goalsFor: 1,
    goalsAgainst: 2,
    goalRows: [{ scorerName: "Mandy Kalmeijer", assistName: "Melissa Rietveld" }],
    mvpRaw: "shared: Mandy Kalmeijer and Anouk Aafjes",
  },
  {
    kickoffIso: "2026-03-14T12:00:00.000Z",
    opponent: "Wieringermeer VR3",
    isHome: true,
    goalsFor: 3,
    goalsAgainst: 4,
    goalRows: [
      { scorerName: "Danique van Heeringen", assistName: "Emma de Mie" },
      { scorerName: "Mandy Kalmeijer", assistName: "Melissa Rietveld" },
      { scorerName: "Mandy Kalmeijer", assistName: "Shura Nieboer" },
    ],
    mvpRaw: "Mandy Kalmeijer",
  },
];
