import type { DecisionLabSession } from "@/lib/decision-lab/types";
import { filmIdsForSlug } from "@/lib/decision-lab/films/dedicated/ids";

/** Dedicated film pitch wiring — no generic press-good / connected-team fallback. */
function dedicatedPitch(
  slug: string,
  titles: {
    badTitle: string;
    goodTitle: string;
    badConsequence?: string;
    goodConsequence?: string;
  },
) {
  const ids = filmIdsForSlug(slug);
  return {
    liveSituationId: ids.live,
    badSituationId: ids.bad,
    goodSituationId: ids.good,
    badTitle: titles.badTitle,
    goodTitle: titles.goodTitle,
    badConsequence:
      titles.badConsequence ?? "Verkeerde prioriteit — ruimte of timing valt tegen ons.",
    goodConsequence:
      titles.goodConsequence ?? "Juiste prioriteit — team blijft speelbaar.",
  } as const;
}

/** @deprecated kept name for minimal catalog churn — now resolves dedicated films */
function pressPitch(
  slug: string,
  titles?: Partial<{
    badTitle: string;
    goodTitle: string;
    badConsequence: string;
    goodConsequence: string;
  }>,
) {
  return dedicatedPitch(slug, {
    badTitle: titles?.badTitle ?? "Recht naar de bal",
    goodTitle: titles?.goodTitle ?? "Binnenkant dicht",
    badConsequence:
      titles?.badConsequence ?? "Binnenlijn blijft open — hun middenvelder komt vrij.",
    goodConsequence:
      titles?.goodConsequence ?? "Binnenlijn dicht — bal gaat terug of wijd.",
  });
}

/** Certified Decision Sessions — product catalog (Orders #1–#18). No new football content. */

function pressChoices(roleLabel: string): DecisionLabSession["choices"] {
  return [
    {
      id: "A",
      label: "Recht naar de bal sprinten",
      correct: false,
      consequence: "Binnenlijn blijft open. Hun middenvelder krijgt de bal.",
      explanation: "Je rent recht op de bal. De pass naar binnen blijft open en onze druk valt weg.",
      errorFix: "Eerst de lijn, dan de bal.",
    },
    {
      id: "B",
      label: "Binnenkant sluiten, buitenom sturen",
      correct: true,
      consequence: "Hun back kan niet naar binnen. Bal gaat terug of wijd.",
      explanation: `Je sluit eerst de binnenlijn als ${roleLabel}. Daardoor moet hun back naar buiten of terug.`,
    },
    {
      id: "C",
      label: "Terugzakken naast de middenvelders",
      correct: false,
      consequence: "Hun back krijgt tijd. Opties blijven open.",
      explanation: "Je zakt weg zonder de lijn te sluiten. Dit moment vraagt gerichte druk.",
      errorFix: "First press mét binnenkant dicht.",
    },
  ];
}

export const DECISION_LAB_SESSIONS: DecisionLabSession[] = [
  {
    id: "FDL-GS-INSIDE-CLOSE-RB-PRESS-V1",
    order: 1,
    slug: "binnenkant-dicht-rw",
    title: "Binnenkant sluiten bij druk op hun back",
    playerTitle: "Hun back krijgt de bal — wat doe jij eerst?",
    subtitle: "Golden Session · Rechtsbuiten · Force outside",
    wave: "pressing",
    difficulty: "Basis",
    durationMin: 3,
    durationMax: 4,
    primaryRole: "Rechtsbuiten",
    cue: "Binnenkant dicht",
    lp: "LP-002",
    whyItMatters:
      "Als jij recht op de bal sprint, speelt hun back naar binnen en stort onze press in. Eén prioriteit: eerst de binnenlijn dicht.",
    learningGoals: [
      "Trigger herkennen: bal naar hun back",
      "Eerste prioriteit: binnenkant dicht",
      "Gebogen press kiezen boven rechte sprint",
      "Cue benoemen: Binnenkant dicht",
    ],
    scanPrompt: "Welke lijn is het gevaarlijkst open?",
    scanHints: ["Bal naar hun back?", "Iemand vrij naar binnen?", "Ren jij recht of sluit je eerst de lijn?"],
    decisionPrompt: "Kies je eerste actie als rechtsbuiten.",
    choices: pressChoices("rechtsbuiten"),
    tree: {
      question: "Bal naar hun back onder onze press?",
      branches: [
        { label: "Binnenlijn dicht → stuur buiten", result: "Juiste first action", tone: "good" },
        { label: "Recht op de bal", result: "Press breekt — binnen open", tone: "bad" },
        { label: "Wegzakken", result: "Trigger gemist", tone: "bad" },
      ],
    },
    executionSteps: [
      "Aanloop vanuit de binnenkant van de escape",
      "Binnenlijn dicht vóór maximale baljacht",
      "Buiten / touchline mag open — stuurkant",
      "Rem vóór het duel; 8 dekt de volgende optie",
    ],
    coaching: ["Back krijgt ‘m — binnenkant dicht.", "Eerst de lijn, dan het duel.", "Niet: pak de bal."],
    summary: "Voortaan: back ontvangt → eerst binnenlijn dicht. Cue: Binnenkant dicht.",
    takeaway: "Eerst de binnenlijn dicht — dan pas de bal.",
    pitch: {
      liveSituationId: "fdl-gs-inside-close-live",
      badSituationId: "fdl-gs-inside-close-bad",
      goodSituationId: "fdl-gs-inside-close-good",
      badTitle: "Recht naar de bal",
      goodTitle: "Binnenkant dicht",
      badConsequence: "Binnenlijn blijft open — hun middenvelder komt vrij.",
      goodConsequence: "Binnenlijn dicht — bal gaat terug of wijd.",
    },
    nextSessionId: "FDL-DS-INSIDE-CLOSE-LW-PRESS-V1",
    prevSessionId: null,
  },
  {
    id: "FDL-DS-INSIDE-CLOSE-LW-PRESS-V1",
    order: 2,
    slug: "binnenkant-dicht-lw",
    title: "Binnenkant sluiten — spiegel (LW)",
    playerTitle: "Hun back krijgt de bal — wat doe jij eerst?",
    subtitle: "Spiegel · Linksbuiten · Zelfde wet",
    wave: "pressing",
    difficulty: "Basis",
    durationMin: 3,
    durationMax: 4,
    primaryRole: "Linksbuiten",
    cue: "Binnenkant dicht",
    lp: "LP-002",
    whyItMatters: "Zelfde prioriteit op de andere flank — geen nieuwe wet.",
    learningGoals: [
      "Trigger herkennen op linkerflank",
      "Zelfde first action als rechts",
      "Cue: Binnenkant dicht",
      "Transfer: beide kanten covered",
    ],
    scanPrompt: "Welke lijn is het gevaarlijkst open?",
    scanHints: ["Bal naar hun RB?", "Binnenoptie vrij?", "Curve of rechte sprint?"],
    decisionPrompt: "Kies je eerste actie als linksbuiten.",
    choices: pressChoices("linksbuiten"),
    tree: {
      question: "Bal naar hun back (links)?",
      branches: [
        { label: "Binnenkant dicht", result: "Juist", tone: "good" },
        { label: "Rechte sprint", result: "Binnen open", tone: "bad" },
        { label: "Wegzakken", result: "Trigger gemist", tone: "bad" },
      ],
    },
    executionSteps: ["Inside-out curve", "Binnenlijn dicht", "Stuur buitenom", "Second press dekt mee"],
    coaching: ["Ook links: binnenkant dicht."],
    summary: "Ook links: back ontvangt → binnenlijn dicht.",
    takeaway: "Eerst de binnenlijn dicht — dan pas de bal.",
    pitch: pressPitch("binnenkant-dicht-lw", { badTitle: "Rechte sprint (LW)", goodTitle: "Binnenkant dicht (LW)" }),
    nextSessionId: "FDL-DS-INSIDE-CLOSE-RW-DECISION-V1",
    prevSessionId: "FDL-GS-INSIDE-CLOSE-RB-PRESS-V1",
  },
  {
    id: "FDL-DS-INSIDE-CLOSE-RW-DECISION-V1",
    order: 3,
    slug: "binnenkant-dicht-decision",
    title: "Wat doe jij eerst? (Decision)",
    playerTitle: "Hun back krijgt de bal — wat doe jij eerst?",
    subtitle: "LP-003 · Stabiele wedstrijdkeuze",
    wave: "pressing",
    difficulty: "Midden",
    durationMin: 3,
    durationMax: 5,
    primaryRole: "Rechtsbuiten",
    cue: "Binnenkant dicht",
    lp: "LP-003",
    whyItMatters: "Herkennen is niet genoeg — je moet de juiste first action kiezen vóór uitleg.",
    learningGoals: [
      "Kiezen onder eerlijke freeze",
      "Gevolg voorspellen",
      "Prioriteit vasthouden",
      "Cue stabiel recallen",
    ],
    scanPrompt: "Wat gebeurt er als de binnenlijn open blijft?",
    scanHints: ["Progressive inside?", "Press valt weg?", "Wat kies jij eerst?"],
    decisionPrompt: "Kies je eerste actie als rechtsbuiten.",
    choices: pressChoices("rechtsbuiten"),
    tree: {
      question: "Wat is first priority?",
      branches: [
        { label: "Binnenlijn dicht", result: "Juist", tone: "good" },
        { label: "Bal jagen", result: "Fout", tone: "bad" },
        { label: "Wegzakken", result: "Fout", tone: "bad" },
      ],
    },
    executionSteps: ["Kies vóór je rent", "Inside-out", "Rem vóór duel", "Team sluit aan"],
    coaching: ["Beslis eerst — Binnenkant dicht."],
    summary: "Beslis eerst: binnenlijn dicht.",
    takeaway: "Eerst kiezen: lijn dicht — dan pas de bal.",
    pitch: pressPitch("binnenkant-dicht-decision"),
    nextSessionId: "FDL-DS-SECOND-PRESS-8-V1",
    prevSessionId: "FDL-DS-INSIDE-CLOSE-LW-PRESS-V1",
  },
  {
    id: "FDL-DS-SECOND-PRESS-8-V1",
    order: 4,
    slug: "tweede-druk-8",
    title: "Tweede druk: binnenoptie dichthouden als 8",
    playerTitle: "RW zet druk — wat doe jij als 8?",
    subtitle: "Teampress · Second press",
    wave: "pressing",
    difficulty: "Midden",
    durationMin: 3,
    durationMax: 5,
    primaryRole: "8",
    cue: "Passlijn dicht",
    lp: "LP-002",
    whyItMatters: "Zonder 8 die de binnenoptie sluit, is de RW-press solo — en nutteloos.",
    learningGoals: [
      "Herkennen wanneer RW first press zet",
      "Binnenoptie dichthouden",
      "Niet meesprinten op de back",
      "Cue: Passlijn dicht",
    ],
    scanPrompt: "Wie staat vrij als jij meesprint?",
    scanHints: ["Hun 8/CM?", "Halfspace?", "Jouw job vs RW?"],
    decisionPrompt: "Kies je eerste actie als 8.",
    choices: [
      {
        id: "A",
        label: "Meesprinten op hun back",
        correct: false,
        consequence: "Twee op de back — middenvelder vrij.",
        explanation: "Je sprint mee. De pass naar binnen blijft open.",
        errorFix: "Cover de binnenoptie.",
      },
      {
        id: "B",
        label: "Binnenoptie dichthouden",
        correct: true,
        consequence: "Hun LB kan niet schoon naar binnen.",
        explanation: "Je sluit de volgende passlijn. Daardoor helpt de druk van de RW echt.",
      },
      {
        id: "C",
        label: "Blijven staan en toekijken",
        correct: false,
        consequence: "Ontvanger blijft vrij.",
        explanation: "Je blijft staan. Hun middenvelder krijgt de bal tussen ons.",
        errorFix: "Beweeg naar de optie.",
      },
    ],
    tree: {
      question: "RW first press?",
      branches: [
        { label: "8 sluit binnenoptie", result: "Juist", tone: "good" },
        { label: "Meejagen", result: "Solo + gat", tone: "bad" },
        { label: "Stilstaan", result: "Ontvanger vrij", tone: "bad" },
      ],
    },
    executionSteps: ["Stap naar binnenontvanger", "Ontken progressive inside", "RW houdt first press", "6 houdt centrum"],
    coaching: ["RW drukt — jij sluit de binnenoptie."],
    summary: "Als 8: niet meejagen. Sluit de binnenoptie.",
    takeaway: "Tweede druk = binnenoptie dicht — niet dubbel op de back.",
    pitch: pressPitch("tweede-druk-8", {
      badTitle: "8 jaagt mee",
      goodTitle: "8 sluit binnenoptie",
      badConsequence: "Binnenontvanger vrij tussen de linies.",
      goodConsequence: "Binnenpass ontkend — press blijft staan.",
    }),
    nextSessionId: "FDL-DS-DEPTH-COVER-RB-V1",
    prevSessionId: "FDL-DS-INSIDE-CLOSE-RW-DECISION-V1",
  },
  {
    id: "FDL-DS-DEPTH-COVER-RB-V1",
    order: 5,
    slug: "rugdekking-rb",
    title: "Rugdekking: wat doet de back achter de press?",
    playerTitle: "RW zet druk — wat doe jij als rechtsback?",
    subtitle: "Diepte · Last line",
    wave: "verdedigen",
    difficulty: "Basis",
    durationMin: 3,
    durationMax: 4,
    primaryRole: "Rechtsback",
    cue: "Rugdekking",
    lp: "LP-002",
    whyItMatters: "Zonder rugdekking explodeert een goede press in de rug.",
    learningGoals: [
      "Ruimte achter de press zien",
      "Diepte houden i.p.v. meejagen",
      "Cue: Rugdekking",
      "Lijn verbonden houden",
    ],
    scanPrompt: "Waar ontstaat het gat als jij meejagt?",
    scanHints: ["Achter RW?", "Tussen RB–RCB?", "Opp in diepte?"],
    decisionPrompt: "Kies je eerste actie als rechtsback.",
    choices: [
      {
        id: "A",
        label: "Meejagen hoog achter de RW",
        correct: false,
        consequence: "Gat achter de press.",
        explanation: "Je jaagt mee. Achter de RW ontstaat ruimte.",
        errorFix: "Diepte achter RW.",
      },
      {
        id: "B",
        label: "Diepte houden achter de press",
        correct: true,
        consequence: "Press staat — geen makkelijke bal in de rug.",
        explanation: "Je houdt de rug dicht. Daardoor kan de RW druk zetten zonder gat achterin.",
      },
      {
        id: "C",
        label: "Vast blijven staan zonder aansluiting",
        correct: false,
        consequence: "Geen aansluiting — te laat.",
        explanation: "Je blijft te ver staan. De lijn sluit niet aan op de press.",
        errorFix: "Stap mee, blijf cover.",
      },
    ],
    tree: {
      question: "RW first press?",
      branches: [
        { label: "Diepte / rugdekking", result: "Juist", tone: "good" },
        { label: "Meejagen", result: "Gat", tone: "bad" },
        { label: "Te diep stil", result: "Laat", tone: "bad" },
      ],
    },
    executionSteps: ["Blijf achter first press", "Stap mee zonder jagen", "Verbind met RCB", "Opp LW perifeer"],
    coaching: ["RW drukt — jij houdt de rug."],
    summary: "Als back: niet meejagen. Houd diepte.",
    takeaway: "Goede press sterft zonder rugdekking.",
    pitch: pressPitch("rugdekking-rb", {
      badTitle: "RB jaagt mee",
      goodTitle: "RB houdt diepte",
      badConsequence: "Ruimte achter de press.",
      goodConsequence: "Lijn connected — press veilig.",
    }),
    nextSessionId: "FDL-DS-ST-STEER-PIN-V1",
    prevSessionId: "FDL-DS-SECOND-PRESS-8-V1",
  },
];

/** Remaining Orders #6–#18 — compact certified catalog entries */
const REST: Omit<DecisionLabSession, "prevSessionId" | "nextSessionId">[] = [
  {
    id: "FDL-DS-ST-STEER-PIN-V1",
    order: 6,
    slug: "spits-stuurt",
    title: "Spits stuurt — niet solo op hun back jagen",
    playerTitle: "Bal naar hun back — wat doe jij als spits?",
    subtitle: "First line · Steer / pin",
    wave: "pressing",
    difficulty: "Midden",
    durationMin: 3,
    durationMax: 4,
    primaryRole: "Spits",
    cue: "Stuurt mee",
    lp: "LP-002",
    whyItMatters: "Solo jagen op hun back opent het centrum — de RW-press wordt geïsoleerd.",
    learningGoals: ["Sturen/pinnen i.p.v. solo hunt", "Cue: Stuurt mee", "First line houden", "RW-press mogelijk maken"],
    scanPrompt: "Wat blijft open als jij solo op de back jaagt?",
    scanHints: ["Centrum?", "LCB-recycle?", "RW alleen?"],
    decisionPrompt: "Kies je eerste actie als spits.",
    choices: [
      { id: "A", label: "Solo op hun back jagen", correct: false, consequence: "Centrum open.", explanation: "Je jaagt solo. Het centrum blijft open.", errorFix: "Stuur/pin." },
      { id: "B", label: "Sturen / pinnen op de opbouw", correct: true, consequence: "Geen makkelijke recycle.", explanation: "Je stuurt mee. De RW kan binnenkant dicht zetten." },
      { id: "C", label: "Wegzakken zonder drukrichting", correct: false, consequence: "Geen drukrichting.", explanation: "Je zakt weg. Hun opbouw speelt door.", errorFix: "Blijf first line." },
    ],
    tree: { question: "RW first press?", branches: [{ label: "ST stuurt/pin", result: "Juist", tone: "good" }, { label: "Solo jagen", result: "Fout", tone: "bad" }, { label: "Wegzakken", result: "Fout", tone: "bad" }] },
    executionSteps: ["First line houden", "Snijd centrale escape", "Niet op LB-tenen", "10 screens mee"],
    coaching: ["RW drukt — jij stuurt mee."],
    summary: "Als spits: niet solo jagen. Stuur mee.",
    takeaway: "Spits stuurt — RW drukt.",
    pitch: pressPitch("spits-stuurt", { badTitle: "ST solo jaagt", goodTitle: "ST stuurt mee" }),
  },
  {
    id: "FDL-DS-FAR-SIDE-SQUEEZE-V1",
    order: 7,
    slug: "verre-zijde-knijpt",
    title: "Verre zijde knijpt mee",
    playerTitle: "Druk rechts — wat doe jij links?",
    subtitle: "Compact · Far side",
    wave: "pressing",
    difficulty: "Basis",
    durationMin: 3,
    durationMax: 4,
    primaryRole: "Linksbuiten",
    cue: "Knijp mee",
    lp: "LP-002",
    whyItMatters: "Press is team — ook de verre zijde. Hangen opent de switch.",
    learningGoals: ["Knijpen i.p.v. hoog hangen", "Cue: Knijp mee", "Switch moeilijker maken", "Compact blijven"],
    scanPrompt: "Wat blijft open als jij hoog blijft hangen?",
    scanHints: ["Switch lane?", "Breedte?", "LB connected?"],
    decisionPrompt: "Kies je eerste actie als linksbuiten.",
    choices: [
      { id: "A", label: "Hoog blijven hangen op de flank", correct: false, consequence: "Switch lane open.", explanation: "Je blijft hoog hangen. Links blijft te veel ruimte.", errorFix: "Knijp." },
      { id: "B", label: "Knijpen / aansluiten", correct: true, consequence: "Team smaller — switch moeilijker.", explanation: "Je knijpt mee. Verre zijde hoort bij de press." },
      { id: "C", label: "Helemaal inzaken tot de last line", correct: false, consequence: "Geen tussencompactheid.", explanation: "Je zakt te diep. Het midden blijft open.", errorFix: "Compact, niet verdwijnen." },
    ],
    tree: { question: "Press balzijde rechts?", branches: [{ label: "Knijp mee", result: "Juist", tone: "good" }, { label: "Hoog hangen", result: "Fout", tone: "bad" }, { label: "Te diep", result: "Fout", tone: "bad" }] },
    executionSteps: ["Stap naar binnen", "Blijf speelbaar", "LB knijpt mee", "Geen elastiek"],
    coaching: ["Druk rechts — links knijp mee."],
    summary: "Verre zijde: niet hangen. Knijp mee.",
    takeaway: "Press is team — ook de verre zijde.",
    pitch: pressPitch("verre-zijde-knijpt", { badTitle: "LW hangt hoog", goodTitle: "LW knijpt mee" }),
  },
  {
    id: "FDL-DS-PRESS-ABORT-RECOVER-V1",
    order: 8,
    slug: "niet-doordrukken",
    title: "Niet doordrukken — wanneer stop je de first press?",
    playerTitle: "De press-window is weg — wat doe jij?",
    subtitle: "Abort · Herstel",
    wave: "pressing",
    difficulty: "Hoog",
    durationMin: 3,
    durationMax: 5,
    primaryRole: "Rechtsbuiten",
    cue: "Niet doordrukken",
    lp: "LP-003",
    whyItMatters: "Late jacht is geen goede press — je moet weten wanneer te stoppen.",
    learningGoals: ["Window-weg herkennen", "Afbreken i.p.v. jagen", "Cue: Niet doordrukken", "Bescherm #1–#7"],
    scanPrompt: "Is doordrukken nu nog de juiste first action?",
    scanHints: ["Steun er?", "Bal al inside?", "Te laat?"],
    decisionPrompt: "Kies je eerste actie als rechtsbuiten.",
    choices: [
      { id: "A", label: "Alsnog doordrukken / jagen", correct: false, consequence: "Press broken erger.", explanation: "Je jaagt alsnog. Het centrum of de rug wordt erger.", errorFix: "Afbreken." },
      { id: "B", label: "Afbreken en herstellen", correct: true, consequence: "Schade beperkt.", explanation: "De window was weg. Je drukt niet door. Je herstelt." },
      { id: "C", label: "Stoppen en toekijken", correct: false, consequence: "Geen herstelvorm.", explanation: "Je kijkt toe. Zonder herstel blijft het gat open.", errorFix: "Herstel mee." },
    ],
    tree: { question: "Press-window nog open?", branches: [{ label: "Nee → afbreken", result: "Juist", tone: "good" }, { label: "Alsnog jagen", result: "Fout", tone: "bad" }, { label: "Passief", result: "Fout", tone: "bad" }] },
    executionSteps: ["Stop volle jacht", "Goal-side herstel", "Geen kamikaze", "Team reorganiseert"],
    coaching: ["Window weg — niet doordrukken."],
    summary: "Goede press stopt ook op tijd.",
    takeaway: "Juiste press weet wanneer te stoppen.",
    pitch: pressPitch("niet-doordrukken", {
      badTitle: "Alsnog jagen",
      goodTitle: "Afbreken / herstel",
      badConsequence: "Overrun — press broken erger.",
      goodConsequence: "Vorm terug — schade beperkt.",
    }),
  },
  {
    id: "FDL-DS-INSIDE-CLOSE-RW-PRESSURE-V1",
    order: 9,
    slug: "binnenkant-onder-druk",
    title: "Zelfde prioriteit — minder tijd",
    playerTitle: "Sneller moment — wat doe jij eerst?",
    subtitle: "LP-004 · Pressure",
    wave: "pressing",
    difficulty: "Hoog",
    durationMin: 3,
    durationMax: 4,
    primaryRole: "Rechtsbuiten",
    cue: "Binnenkant dicht",
    lp: "LP-004",
    whyItMatters: "Druk verandert de wet niet — paniek mag niet winnen.",
    learningGoals: ["Zelfde first action onder tempo", "Niet panikeren naar bal", "Cue vasthouden", "Bridge naar omschakeling"],
    scanPrompt: "Minder tijd. Wat blijft eerst?",
    scanHints: ["Binnenlijn?", "Niet de bal?", "Zelfde prioriteit?"],
    decisionPrompt: "Kies je eerste actie als rechtsbuiten.",
    choices: pressChoices("rechtsbuiten"),
    tree: { question: "Tijddruk — first priority?", branches: [{ label: "Binnenkant dicht", result: "Juist", tone: "good" }, { label: "Paniek sprint", result: "Fout", tone: "bad" }, { label: "Wegzakken", result: "Fout", tone: "bad" }] },
    executionSteps: ["Sneller starten na trigger", "Zelfde inside-out", "Rem blijft", "Prioriteit gelijk"],
    coaching: ["Sneller moment —zelfde cue."],
    summary: "Druk verandert de prioriteit niet.",
    takeaway: "Minder tijd —zelfde first action.",
    pitch: pressPitch("binnenkant-onder-druk"),
  },
  {
    id: "FDL-DS-COUNTERPRESS-FIRST-ACTION-V1",
    order: 10,
    slug: "balverlies-direct-druk",
    title: "Balverlies — wat is je eerste actie?",
    playerTitle: "Bal kwijt — wat doe jij eerst?",
    subtitle: "Omschakeling · Direct druk",
    wave: "omschakeling",
    difficulty: "Midden",
    durationMin: 3,
    durationMax: 5,
    primaryRole: "Dichtste speelster",
    cue: "Direct druk",
    lp: "LP-002",
    whyItMatters: "Na verlies wint wie meteen handelt — niet wie terugkijkt.",
    learningGoals: ["Balverlies herkennen", "Direct druk i.p.v. stoppen", "Cue: Direct druk", "Keten: press → loss"],
    scanPrompt: "Wie is nu het dichtst bij hun nieuwe bal?",
    scanHints: ["Jij?", "Niet eigen doel?", "Window seconden?"],
    decisionPrompt: "Kies je eerste actie na balverlies.",
    choices: [
      { id: "A", label: "Terugkijken / stoppen", correct: false, consequence: "Opp krijgt tijd.", explanation: "Je stopt. Zij krijgen tijd.", errorFix: "Direct druk." },
      { id: "B", label: "Direct druk zetten", correct: true, consequence: "Geen gratis tijd voor hen.", explanation: "Je reageert meteen. Eerste actie na verlies: direct druk." },
      { id: "C", label: "Wegsprinten naar eigen helft", correct: false, consequence: "Gat voor progressie.", explanation: "Je rent weg. Voor hen ontstaat ruimte.", errorFix: "Blijf dichtbij." },
    ],
    tree: { question: "Bal net kwijt?", branches: [{ label: "Direct druk", result: "Juist", tone: "good" }, { label: "Stoppen", result: "Fout", tone: "bad" }, { label: "Wegrennen", result: "Fout", tone: "bad" }] },
    executionSteps: ["Orient op nieuwe balhouder", "Directe druk/compact", "Geen discussie", "Team schuift mee"],
    coaching: ["Bal kwijt — direct druk."],
    summary: "Na verlies: niet bevriezen.",
    takeaway: "Bal kwijt → meteen handelen.",
    pitch: pressPitch("balverlies-direct-druk", { badTitle: "Stoppen", goodTitle: "Direct druk" }),
  },
  {
    id: "FDL-DS-REST-DEFENCE-AFTER-BEATEN-V1",
    order: 11,
    slug: "restverdediging",
    title: "Geslagen in de press — wat doet de restverdediging?",
    playerTitle: "Press geslagen — wat doe jij achterin?",
    subtitle: "Overleven · Last line",
    wave: "omschakeling",
    difficulty: "Hoog",
    durationMin: 3,
    durationMax: 5,
    primaryRole: "Rechtsback",
    cue: "Restverdediging",
    lp: "LP-003",
    whyItMatters: "Na een geslagen press bepaalt de lijn of het 0–1 wordt.",
    learningGoals: ["Press broken herkennen", "Compact herstel", "Cue: Restverdediging", "Niet solo najagen"],
    scanPrompt: "Wat gebeurt er met de lijn als jij alleen achter de bal rent?",
    scanHints: ["Gat RB–RCB?", "Diepte?", "Solo chase?"],
    decisionPrompt: "Kies je eerste actie als rechtsback.",
    choices: [
      { id: "A", label: "Individueel najagen achter de bal", correct: false, consequence: "Lijn breekt.", explanation: "Je jaagt solo. Achter jou ontstaat ruimte.", errorFix: "Compact." },
      { id: "B", label: "Compact herstellen", correct: true, consequence: "Lijn blijft staan.", explanation: "Je herstelt compact. Najagen alleen maakt het gat groter." },
      { id: "C", label: "Vast blijven staan / afhaken", correct: false, consequence: "Geen aansluiting.", explanation: "Je haakt af. Zonder herstel blijft het gevaar.", errorFix: "Stap mee in vorm." },
    ],
    tree: { question: "Press broken?", branches: [{ label: "Restverdediging", result: "Juist", tone: "good" }, { label: "Solo jacht", result: "Fout", tone: "bad" }, { label: "Afhaken", result: "Fout", tone: "bad" }] },
    executionSteps: ["Drop/compact met partner", "Goal-side", "Geen wilde jacht", "RW herstelt mee"],
    coaching: ["Press geslagen — restverdediging."],
    summary: "Geslagen press: niet paniekjagen.",
    takeaway: "Overleven na de press is ook een beslissing.",
    pitch: pressPitch("restverdediging", { badTitle: "Solo najagen", goodTitle: "Compact herstel" }),
  },
  {
    id: "FDL-DS-FIRST-PASS-AFTER-WIN-V1",
    order: 12,
    slug: "eerste-pass-na-win",
    title: "Bal terug — eerste pass vooruit of veilig?",
    playerTitle: "Bal terug — welke pass eerst?",
    subtitle: "Win → first pass",
    wave: "omschakeling",
    difficulty: "Midden",
    durationMin: 3,
    durationMax: 5,
    primaryRole: "8",
    cue: "Eerste pass",
    lp: "LP-003",
    whyItMatters: "Bal terug is pas winst na de juiste eerste pass.",
    learningGoals: ["Scan vooruit open/dicht", "Passende first pass", "Cue: Eerste pass", "Keten afronden"],
    scanPrompt: "Is de vooruitlijn open of dicht?",
    scanHints: ["Progressive vrij?", "Veilige steun?", "Druk dichtbij?"],
    decisionPrompt: "Kies je eerste pass.",
    choices: [
      { id: "A", label: "Blind vooruit forceren", correct: false, consequence: "Bal kwijt / chaos.", explanation: "Je forceert vooruit in dichte druk.", errorFix: "Scan → passende pass." },
      { id: "B", label: "Veilige / passende eerste pass", correct: true, consequence: "Bal blijft van ons.", explanation: "Je zag dat vooruit dicht was. Je speelt veilig eerst." },
      { id: "C", label: "Aarzelen / stilzetten", correct: false, consequence: "Tempo dood — druk komt.", explanation: "Je aarzelt. Zonder pass komt hun druk terug.", errorFix: "Beslis en speel." },
    ],
    tree: { question: "Vooruit speelbaar?", branches: [{ label: "Nee → veilig", result: "Juist (deze les)", tone: "good" }, { label: "Blind forceren", result: "Fout", tone: "bad" }, { label: "Aarzelen", result: "Fout", tone: "bad" }] },
    executionSteps: ["Scan 1 beat", "Speel wat scan toelaat", "Geen paniek-hoogte", "Team biedt steun"],
    coaching: ["Bal terug — scan, dan eerste pass."],
    summary: "Na win: niet blind vooruit.",
    takeaway: "Bal terug is pas winst na de juiste eerste pass.",
    pitch: pressPitch("eerste-pass-na-win", {
      badTitle: "Blind forceren",
      goodTitle: "Passende eerste pass",
      badConsequence: "Bal weer kwijt.",
      goodConsequence: "Bal blijft van ons.",
    }),
  },
  {
    id: "FDL-DS-BUILD-UNDER-PRESS-SAFE-V1",
    order: 13,
    slug: "opbouw-speel-veilig",
    title: "Opbouw onder druk — welke optie eerst?",
    playerTitle: "Onder druk — welke pass eerst?",
    subtitle: "Opbouw · Speel veilig",
    wave: "opbouw",
    difficulty: "Midden",
    durationMin: 3,
    durationMax: 5,
    primaryRole: "Centrale verdediger",
    cue: "Speel veilig",
    lp: "LP-002",
    whyItMatters: "Onder hun press forceren = bal kwijt. Zelfde scan als pressing — andere rol.",
    learningGoals: ["Dichte vooruitlijn herkennen", "Veilige pass kiezen", "Cue: Speel veilig", "Bridge naar #14"],
    scanPrompt: "Welke lijn is dicht — en wat blijft speelbaar?",
    scanHints: ["Vooruit dicht?", "Kant/terug vrij?", "Niet forceren?"],
    decisionPrompt: "Kies je eerste pass in de opbouw.",
    choices: [
      { id: "A", label: "Blind forceren door het press", correct: false, consequence: "Bal kwijt.", explanation: "Je forceert door het press.", errorFix: "Eerst veilig." },
      { id: "B", label: "Veilige / circulatie-pass", correct: true, consequence: "Bal blijft van ons.", explanation: "Je zag de dichte lijn. Je speelt veilig eerst." },
      { id: "C", label: "Paniek-hoog / long zonder scan", correct: false, consequence: "Controle weg.", explanation: "Je slaat paniek-hoog zonder scan.", errorFix: "Scan → passende pass." },
    ],
    tree: { question: "Vooruitlijn dicht?", branches: [{ label: "Speel veilig", result: "Juist", tone: "good" }, { label: "Forceren", result: "Fout", tone: "bad" }, { label: "Paniek-long", result: "Fout", tone: "bad" }] },
    executionSteps: ["Scan dichte lijn", "Speel vrije steun", "Geen force corridor", "Team biedt hoeken"],
    coaching: ["Onder druk — speel veilig."],
    summary: "Lijn dicht → speel veilig.",
    takeaway: "Onder druk: eerst de open optie — niet forceren.",
    pitch: pressPitch("opbouw-speel-veilig", {
      badTitle: "Forceren",
      goodTitle: "Speel veilig",
      badConsequence: "Bal kwijt in hun press.",
      goodConsequence: "Circulatie — bal blijft.",
    }),
  },
  {
    id: "FDL-DS-BUILD-BREAK-LINE-V1",
    order: 14,
    slug: "opbouw-lijn-open",
    title: "Lijn open — speel je door of behoud je?",
    playerTitle: "Lijn open — speel je door?",
    subtitle: "Opbouw · Progressive",
    wave: "opbouw",
    difficulty: "Hoog",
    durationMin: 3,
    durationMax: 5,
    primaryRole: "Centrale verdediger",
    cue: "Lijn open",
    lp: "LP-003",
    whyItMatters: "Alleen veilig is niet genoeg — speel door wanneer het kan.",
    learningGoals: ["Open lijn herkennen", "Door spelen", "Cue: Lijn open", "Balans met #13"],
    scanPrompt: "Is de progressieve lijn nu open?",
    scanHints: ["Na hun shift?", "Ontvanger vrij?", "Window?"],
    decisionPrompt: "Kies je eerste actie in de opbouw.",
    choices: [
      { id: "A", label: "Toch alleen veilig zonder noodzaak", correct: false, consequence: "Progressie gemist.", explanation: "Je blijft onnodig veilig.", errorFix: "Speel de open lijn." },
      { id: "B", label: "Door de open lijn spelen", correct: true, consequence: "Progressie.", explanation: "Je zag de open lijn. Je speelt door." },
      { id: "C", label: "Aarzelen tot de lijn weer dicht is", correct: false, consequence: "Window dicht.", explanation: "Je aarzelt. De lijn gaat weer dicht.", errorFix: "Beslis en speel." },
    ],
    tree: { question: "Lijn open?", branches: [{ label: "Speel door", result: "Juist", tone: "good" }, { label: "Onnodig veilig", result: "Fout", tone: "bad" }, { label: "Aarzelen", result: "Fout", tone: "bad" }] },
    executionSteps: ["Scan na shift", "Speel progressive", "Tempo/gewicht", "Geen aarzeling"],
    coaching: ["Lijn open — speel door."],
    summary: "Lijn open → speel door.",
    takeaway: "Veilig toen het moest — door toen het kan.",
    pitch: pressPitch("opbouw-lijn-open", {
      badTitle: "Onnodig veilig",
      goodTitle: "Speel door",
      badConsequence: "Moment gemist.",
      goodConsequence: "Progressie tussen linies.",
    }),
  },
  {
    id: "FDL-DS-WIDE-1V1-FORCE-OUTSIDE-V1",
    order: 15,
    slug: "flank-1v1-stuur-buiten",
    title: "1v1 op de flank — stuur buiten of laat binnen open?",
    playerTitle: "1v1 op de flank — wat doe jij eerst?",
    subtitle: "Force outside · Flankduel",
    wave: "verdedigen",
    difficulty: "Midden",
    durationMin: 3,
    durationMax: 4,
    primaryRole: "Rechtsback",
    cue: "Stuur buiten",
    lp: "LP-003",
    whyItMatters: "Zelfde idee als press: bescherm binnen — stuur buiten.",
    learningGoals: ["1v1 herkennen", "Force outside", "Cue: Stuur buiten", "Geen vroege dive"],
    scanPrompt: "Welke kant mag open — binnen of buiten?",
    scanHints: ["Binnen gevaarlijk?", "Touchline stuurkant?", "Bodyhoek?"],
    decisionPrompt: "Kies je eerste actie in het flankduel.",
    choices: [
      { id: "A", label: "Square gaan / binnenkant open laten", correct: false, consequence: "Zij komen naar binnen.", explanation: "Je laat binnen open.", errorFix: "Binnen dicht." },
      { id: "B", label: "Binnen dicht, stuur buiten", correct: true, consequence: "Gedwongen naar touchline.", explanation: "Je houdt binnen dicht en stuurt buiten." },
      { id: "C", label: "Te vroeg tackelen zonder lijn", correct: false, consequence: "Uitgespeeld.", explanation: "Je tackelt te vroeg.", errorFix: "Eerst lijn, dan duel." },
    ],
    tree: { question: "1v1 flank?", branches: [{ label: "Stuur buiten", result: "Juist", tone: "good" }, { label: "Binnen open", result: "Fout", tone: "bad" }, { label: "Vroege tackle", result: "Fout", tone: "bad" }] },
    executionSteps: ["Show outside", "Deny inside", "Delay tot steun", "Touchline = exit"],
    coaching: ["1v1 — stuur buiten."],
    summary: "Flankduel: binnen dicht — stuur buiten.",
    takeaway: "Flankduel: binnen dicht — stuur buiten.",
    pitch: pressPitch("flank-1v1-stuur-buiten", { badTitle: "Binnen open", goodTitle: "Stuur buiten" }),
  },
  {
    id: "FDL-DS-HALFSPACE-RECEIVE-NEXT-ACTION-V1",
    order: 16,
    slug: "halfspace-volgende-actie",
    title: "Bal in de halfspace — wat is je volgende actie?",
    playerTitle: "Bal tussen de linies — wat doe jij?",
    subtitle: "Balbezit · Next action",
    wave: "balbezit",
    difficulty: "Hoog",
    durationMin: 3,
    durationMax: 5,
    primaryRole: "10",
    cue: "Volgende actie",
    lp: "LP-003",
    whyItMatters: "Aanname tussen linies is pas begin — stilzetten doodt de kans.",
    learningGoals: ["Halfspace herkennen", "Next action kiezen", "Cue: Volgende actie", "Niet bevriezen"],
    scanPrompt: "Welke optie is het sterkst na je aanname?",
    scanHints: ["Combine?", "Draai?", "Terug?"],
    decisionPrompt: "Kies je volgende actie als 10.",
    choices: [
      { id: "A", label: "Stilzetten tot druk komt", correct: false, consequence: "Kans weg.", explanation: "Je zet stil. Hun druk komt.", errorFix: "Direct volgende actie." },
      { id: "B", label: "Passende volgende actie", correct: true, consequence: "Tempo blijft.", explanation: "Je kiest meteen de volgende actie." },
      { id: "C", label: "Blind forceren / schieten", correct: false, consequence: "Bal kwijt.", explanation: "Je forceert blind.", errorFix: "Scan → passende actie." },
    ],
    tree: { question: "Bal tussen linies?", branches: [{ label: "Next action", result: "Juist", tone: "good" }, { label: "Freeze", result: "Fout", tone: "bad" }, { label: "Blind force", result: "Fout", tone: "bad" }] },
    executionSteps: ["Orient open", "Scan opties", "Speel vóór druk", "Geen freeze"],
    coaching: ["Halfspace — volgende actie."],
    summary: "Niet bevriezen tussen linies.",
    takeaway: "Halfspace: aanname is pas begin — kies de volgende actie.",
    pitch: pressPitch("halfspace-volgende-actie", {
      badTitle: "Stilzetten",
      goodTitle: "Volgende actie",
      badConsequence: "Druk komt — kans weg.",
      goodConsequence: "Tempo en optie benut.",
    }),
  },
  {
    id: "FDL-DS-SWITCH-PLAY-WHEN-V1",
    order: 17,
    slug: "switch-nu",
    title: "Omschakelen van flank — nu of nog niet?",
    playerTitle: "Switch — nu of nog niet?",
    subtitle: "Balbezit · Timing",
    wave: "balbezit",
    difficulty: "Hoog",
    durationMin: 3,
    durationMax: 5,
    primaryRole: "6",
    cue: "Switch nu",
    lp: "LP-003",
    whyItMatters: "Switch is een beslissing — niet een automatisme.",
    learningGoals: ["Switch-window herkennen", "Niet forceren balzijde", "Cue: Switch nu", "Timing"],
    scanPrompt: "Is de verre zijde echt vrij voor een switch?",
    scanHints: ["Verre kant vrij?", "Balzijde vol?", "Lijn speelbaar?"],
    decisionPrompt: "Kies je volgende actie als 6.",
    choices: [
      { id: "A", label: "Forceren balzijde ondanks volle kant", correct: false, consequence: "Vastgelopen.", explanation: "Je forceert balzijde.", errorFix: "Switch wanneer vrij." },
      { id: "B", label: "Switch nu", correct: true, consequence: "Veld opent.", explanation: "Je zag de vrije verre kant. Je switched nu." },
      { id: "C", label: "Te late / slordige switch", correct: false, consequence: "Zij verschuiven mee.", explanation: "Je switched te laat.", errorFix: "Nu — met kwaliteit." },
    ],
    tree: { question: "Switch speelbaar?", branches: [{ label: "Switch nu", result: "Juist", tone: "good" }, { label: "Force balzijde", result: "Fout", tone: "bad" }, { label: "Te laat", result: "Fout", tone: "bad" }] },
    executionSteps: ["Scan verre zijde", "Switch met gewicht", "Niet forceren balzijde", "Teammates klaar"],
    coaching: ["Volle kant — switch nu."],
    summary: "Volle balzijde + vrije verre kant → switch nu.",
    takeaway: "Switch is een beslissing — niet een automatisme.",
    pitch: pressPitch("switch-nu", {
      badTitle: "Force balzijde",
      goodTitle: "Switch nu",
      badConsequence: "Vastgelopen.",
      goodConsequence: "Veld opent.",
    }),
  },
  {
    id: "FDL-DS-BOX-RUN-NEAR-POST-V1",
    order: 18,
    slug: "voorzet-near-post",
    title: "Voorzet komt — welke loop eerst?",
    playerTitle: "Voorzet komt — waar loop jij?",
    subtitle: "Aanvallen · Near post",
    wave: "aanvallen",
    difficulty: "Basis",
    durationMin: 3,
    durationMax: 4,
    primaryRole: "Spits",
    cue: "Near post",
    lp: "LP-002",
    whyItMatters: "Voorzetten belonen wie op tijd in de juiste zone is.",
    learningGoals: ["Voorzet-moment herkennen", "Juiste zone", "Cue: Near post", "Niet toekijken"],
    scanPrompt: "Welke zone moet jij eerst aanvallen?",
    scanHints: ["Near post?", "Te laat?", "Verkeerde diepte?"],
    decisionPrompt: "Kies je loop als spits.",
    choices: [
      { id: "A", label: "Toekijken / te laat starten", correct: false, consequence: "Bal komt zonder jou.", explanation: "Je kijkt toe of start te laat.", errorFix: "Loop earlier." },
      { id: "B", label: "Near-post / juiste zone aanvallen", correct: true, consequence: "Dreiging in de juiste ruimte.", explanation: "Je valt de juiste zone aan." },
      { id: "C", label: "Verkeerde zone (te diep/far)", correct: false, consequence: "Geen dreiging.", explanation: "Je loopt de verkeerde zone.", errorFix: "Near post eerst." },
    ],
    tree: { question: "Voorzet komt?", branches: [{ label: "Near post", result: "Juist", tone: "good" }, { label: "Toekijken", result: "Fout", tone: "bad" }, { label: "Verkeerde zone", result: "Fout", tone: "bad" }] },
    executionSteps: ["Timing vóór contact", "Attack near-post", "Body open", "Niet ballwatch buiten"],
    coaching: ["Voorzet — near post."],
    summary: "Near post / juiste zone. Eerste release compleet.",
    takeaway: "Voorzet: eerst de juiste zone — niet toekijken.",
    pitch: pressPitch("voorzet-near-post", {
      badTitle: "Toekijken",
      goodTitle: "Near post",
      badConsequence: "Bal zonder dreiging.",
      goodConsequence: "Aanwezig in scoringszone.",
    }),
  },
];

function withLinks(list: DecisionLabSession[]): DecisionLabSession[] {
  return list.map((s, i) => ({
    ...s,
    prevSessionId: i > 0 ? list[i - 1]!.id : null,
    nextSessionId: i < list.length - 1 ? list[i + 1]!.id : null,
  }));
}

const COMBINED = withLinks([
  ...DECISION_LAB_SESSIONS,
  ...REST.map((s) => ({ ...s, prevSessionId: null, nextSessionId: null })),
]);

export function listDecisionLabSessions(): DecisionLabSession[] {
  return COMBINED;
}

export function getDecisionLabSession(idOrSlug: string): DecisionLabSession | undefined {
  return COMBINED.find((s) => s.id === idOrSlug || s.slug === idOrSlug);
}

export function listDecisionLabSessionParams(): { sessionId: string }[] {
  return COMBINED.map((s) => ({ sessionId: s.slug }));
}

export const DECISION_LAB_WAVE_LABEL: Record<DecisionLabSession["wave"], string> = {
  pressing: "Pressing",
  omschakeling: "Omschakeling",
  opbouw: "Opbouw",
  balbezit: "Balbezit",
  verdedigen: "Verdedigen",
  aanvallen: "Aanvallen",
};
