import type { AcademyCategory } from "@/lib/academie/types";

/**
 * Statische categoriedefinities — enige bron voor Academy Home en routing.
 * Omschrijvingen beschrijven de IA-rol, geen voetbalinhoud.
 */
export const ACADEMY_CATEGORY_DEFINITIONS: AcademyCategory[] = [
  {
    id: "cat.voetbalvisie",
    slug: "onze-voetbalvisie",
    title: "Onze Voetbalvisie",
    description: "Visie en identiteit van het team — het startpunt van de Academy.",
    icon: "🎯",
    order: 1,
    visible: true,
    comingSoon: true,
  },
  {
    id: "cat.speelwijze",
    slug: "speelwijze",
    title: "Speelwijze",
    description: "Hoe we het spel benaderen — tactische en technische lijn op hoofdniveau.",
    icon: "⚽",
    order: 2,
    visible: true,
    comingSoon: true,
  },
  {
    id: "cat.posities",
    slug: "posities",
    title: "Posities",
    description: "Per positie uitgelegd — rol, taken en wat er van je wordt verwacht.",
    icon: "📍",
    order: 3,
    visible: true,
    comingSoon: true,
  },
  {
    id: "cat.teamprincipes",
    slug: "teamprincipes",
    title: "Teamprincipes",
    description: "Afspraken en waarden waar we als team op staan — samenhangend overzicht.",
    icon: "🤝",
    order: 4,
    visible: true,
    comingSoon: true,
  },
  {
    id: "cat.wedstrijden",
    slug: "wedstrijden",
    title: "Wedstrijden",
    description: "Alles rondom wedstrijddagen — voorbereiding, structuur en evaluatie.",
    icon: "🏟️",
    order: 5,
    visible: true,
    comingSoon: true,
  },
  {
    id: "cat.trainingen",
    slug: "trainingen",
    title: "Trainingen",
    description: "Trainingsopbouw en werkvormen — per thema en onderwerp uitgewerkt.",
    icon: "📋",
    order: 6,
    visible: true,
    comingSoon: true,
  },
  {
    id: "cat.kennisbank",
    slug: "kennisbank",
    title: "Kennisbank",
    description: "Naslagwerk en referentiemateriaal — alles terugvinden op één plek.",
    icon: "📚",
    order: 7,
    visible: true,
    comingSoon: true,
  },
  {
    id: "cat.media",
    slug: "media",
    title: "Media",
    description: "Beeld en media — visuele uitleg en ondersteunend materiaal.",
    icon: "🎬",
    order: 8,
    visible: true,
    comingSoon: true,
  },
  {
    id: "cat.quiz-toetsing",
    slug: "quiz-toetsing",
    title: "Quiz & Toetsing",
    description: "Kennis testen — quizzen en toetsing om je begrip te checken.",
    icon: "✅",
    order: 9,
    visible: true,
    comingSoon: true,
  },
];
